[package]
name = "google-load-parser"
version = "0.1.0"
authors = ["SLMT <sam123456777@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1"
clap = "2"
log = "0.4"
pretty_env_logger = "0.3"
libflate = "0.1"